bachmannpatrick/CLVTools

.github/workflows/Tests.yaml
tests/testthat/helper_testthat_runability_common.R
tests/testthat/helper_testthat_runability_nocov.R
tests/testthat/helper_testthat_runability_staticcov.R

Skip less relevant tests which take a long time, unless on release branch. 
Use skip_on_ci(). Set env variable CI='' if on release branch.

Reduce tests on CI

---

R/class_clv_data_staticcovariates.R
R/f_clvfitted_inputchecks.R
R/f_generics_clvfittedtransactionsstaticcov_estimate.R
R/f_interface_setdynamiccovariates.R
R/f_interface_setstaticcovariates.R
tests/testthat/helper_testthat_runability_staticcov.R
tests/testthat/test_correctness_clvdata_setdynamiccov.R
tests/testthat/test_correctness_clvdata_setstaticcov.R

Cannot estimate models if cov names are syntactically invalid (contain spaces, start with number) etc

Bugfix: Invalid covariate names

---

src/clv_vectorized.cpp
src/clv_vectorized.h
src/pnbd.cpp
tests/testthat/helper_s3_fitted_predict.R
tests/testthat/test_correctness_pnbd.R

Use the gsl's implementation of the confluent hypergeometric function of the second kind instead of the currently used two-part representation involving the hyp1F1. See #171

PNBD DERT numerical stability

---

R/f_clvdata_inputchecks.R
R/f_clvfitted_inputchecks.R
R/f_generics_clvfittedtransactions.R
R/f_interface_clvdata.R
R/f_s3generics_clvdata_plot.R
R/f_s3generics_clvfittedtransactions_plot.R
man/plot.clv.data.Rd
man/plot.clv.fitted.transactions.Rd
tests/testthat/helper_inputchecks_single_logical.R
tests/testthat/helper_s3_fitted.R
tests/testthat/helper_s3_fitted_plot.R
tests/testthat/helper_s3_fitted_predict.R
tests/testthat/helper_testthat_consistency.R
tests/testthat/helper_testthat_correctness_clvfitted.R
tests/testthat/helper_testthat_inputchecks_nocov.R
tests/testthat/helper_testthat_runability_clvfitted.R
tests/testthat/helper_testthat_runability_dynamiccov.R
tests/testthat/helper_testthat_runability_nocov.R
tests/testthat/helper_testthat_runability_spending.R
tests/testthat/test_inputchecks_clvdata_clvdata.R
tests/testthat/test_inputchecks_clvdata_plot.R
tests/testthat/test_inputchecks_clvdata_setdynamiccov.R
tests/testthat/test_inputchecks_clvdata_setstaticcov.R
tests/testthat/test_inputchecks_plot_transactions.R
tests/testthat/test_inputchecks_predict_transactions.R
tests/testthat/test_runability_clvdata_s3.R

Draw other fitted models next to the main one, by specifying them in a new argument `other.models`.
- The idea is to first collect plot data from all models and concatenate it to a single data.table. This table is then used for plotting. The data of the main model is collected with actuals (if desired), other models are always without actuals. Requires plotting output to be in long format for all plots in order to concatenate them. 
- For all models, the data is collected by calling the generic plot(plot=F) with the same arguments as the original call to plot(). This also takes care of all the input checks and replacing clv.data with newdata if it is given.
- No checks that all models were fit on the same clv.data object are done. 
- If no newdata is given, each models own clv.data object …

Draw other models in same plot

---

R/class_clv_data.R
tests/testthat/test_correctness_clvdata_clvdata.R

More memory efficient and faster creation of repeat transactions
- mark transaction number rather than shifting the Date column
- dont order if already sorted by date

Faster creation of repeat transactions

---

R/class_clv_data.R
R/class_clv_gg.R
tests/testthat/test_correctness_clvdata_clvdata.R

- dont create repeat transactions again because resource intensive
- use existing code as test

gg cbs creation: use existing repeat transactions

---

R/f_generics_clvfittedtransactions.R
R/f_interface_predict_clvfittedtransactions.R
man/predict.clv.fitted.transactions.Rd

Add column with the total spending expected for the prediction period (CET*predicted.mean.spending) to facilitate comparison with existing `actual.total.spending`

Predictions: Add column `predicted.total.spending`

---

R/class_clv_data.R
R/f_clvdata_inputchecks.R
R/f_s3generics_clvdata.R
R/f_s3generics_clvdata_plot.R
man-roxygen/template_clvdata_asdatax.R
man-roxygen/template_summary_data.R
man/as.data.frame.clv.data.Rd
man/as.data.table.clv.data.Rd
man/plot.clv.data.Rd
man/summary.clv.data.Rd
tests/testthat/test_correctness_clvdata_s3.R
tests/testthat/test_inputchecks_clvdata_plot.R
tests/testthat/test_runability_clvdata_s3.R

- lowercase for consistency with other parameters in the same methods
- plural for consistency with other methods (nameS.cov.life vs name.date, trans.binS, etc)

clvdata S3 methods: Harmonize `id`/`Id` arguments to `ids`

---

R/pnbd_dyncov_palive.R
tests/testthat/test_correctness_pnbd_dyncov.R

As derived by @JeffNaef . Use LL directly rather than its parts

PNBD dyncov: Improve PAlive numeric stability

---

src/ggomnbd.cpp

Bugfix GGomNBD: Free workspace after not used anymore

---

src/ggomnbd.cpp

Rewrite integral in LL as exp(log()) to improve numerical stability during numerical integration. This also reduces runtime, likely because convergence (error tolerance) is reached earlier.

GGomNBD LL: Improve integral numerical stability

---

R/all_generics.R
R/class_clv_fitted.R
R/class_clv_fitted_spending.R
R/class_clv_pnbd.R
R/class_clv_pnbd_dynamiccov.R
R/class_clv_pnbd_staticcov.R
R/clv_template_controlflow_estimate.R
R/f_generics_clvfitted.R
R/f_generics_clvfitted_estimate.R
R/f_generics_clvfittedspending.R
R/f_generics_clvfittedtransactions.R
R/f_generics_clvfittedtransactionsstaticcov.R
R/f_generics_clvfittedtransactionsstaticcov_estimate.R
R/f_generics_clvpnbddyncov.R
R/f_interface_bootstrappedapply.R
man/clv.bootstrapped.apply.Rd
man/clv.fitted-class.Rd

Replace collecting method call args from the fitted models properties (`clv.fitted.get.model.estimation.interface.args`) with a list which explicitly stores them when estimating the model. This allows to store args such as optimx.args or start parameters and re-use them again when bootstrapping.

Bootstrapping: Store call args in object

---

DESCRIPTION
src/bgnbd.cpp
src/clv_vectorized.cpp
src/clv_vectorized.h
src/ggomnbd.cpp
src/pnbd.cpp

Use native methods offered by armadillo which were not available at time of original implementation.
* `vec_pow()`: Replace with native `arma::pow()`. Available since version 0.11.4.0.1 (2022-10-01).
* `vec_fill()`: replace with native `arma::vec(arma::fill::value())`. Requires RcppArmadillo version 0.10.6.0.0 (2021-07-16) which is lower than already required.
* DESCRIPTION: Update required version for RcppArmadillo to 0.11.4.0.1 (2022-10-01)

RcppArmadillo: Native vec methods

---

R/class_clv_time_date.R
R/class_clv_time_datetime.R
tests/testthat/helper_testthat_correctness_clvtime.R
tests/testthat/test_correctness_clvtime.R

* data read with `data.table::fread` by default stores dates as `data.table::IDate`.
* `clv.time.convert.user.input.to.timepoint`: Add dispatch for `IDate` class.
Closes #255 .

`clv.time`: Accept `data.table::IDate` as inputs

---

R/class_clv_model.R
R/class_clv_model_bgnbd.R
R/class_clv_model_gg.R
R/class_clv_model_ggomnbd_nocov.R
R/class_clv_model_pnbd.R
R/f_generics_clvfitted.R
man/clv.model-class.Rd

Store generics to fit model in `clv.model`. Required during bootstrapping to select method to apply based on clv.model.

Boots: Fix model selection by storing generics to fit model in `clv.model`

---

R/class_clv_model_pnbd_dynamiccov.R

The full `obj` is needed in the correlation interlayer

Fix: Dyncov correlation

---

R/f_generics_clvfittedspending.R
R/f_generics_clvfittedtransactions.R
R/f_interface_bootstrappedapply.R
man/clv.bootstrapped.apply.Rd
tests/testthat/test_correctness_bootstrapping.R
tests/testthat/test_inputchecks_bootstrapping.R
tests/testthat/test_runability_bootstrapping.R

For consistency with `predict(num.boots)`

`clv.bootstrapped.apply`: Rename `num.boot` -> `num.boots`

---

DESCRIPTION

Explicitly name GSL as a external, non-R system dependency

Add `SystemRequirements` to `DESCRIPTION`

---

src/RcppExports.cpp
src/clv_vectorized.cpp
src/clv_vectorized.h

There is no requirement to use RcppGSL vectors to call GSL methods as they are called with scalars.

Replace RcppGSL::Vector with arma::vec

---

R/f_generics_clvfitted.R
R/f_generics_clvfittedspending.R
R/f_generics_clvfittedtransactions.R

- Not required to derive `prediction.end` anymore as bootstrapped data by now keeps holdout period
- Do not use estimated parameters as start params for bootstrapped model fitting anymore

Predict (uncertainty): Refit with exact original specification

---

R/class_clv_model_pnbd_dynamiccov.R

Significantly increase the default number of iterations for dyncov models (`itnmax`) from 3000 to 50000. The previous iteration limit is rather low for NelderMead and in practice was often reached. This likely mislead users to believe that the optimization converged when in reality it only stopped because the max num iterations had been reached.

PNBD Dyncov: Improved optimx defaults (higher `itnmax`)

---

R/f_s3generics_clvfitted.R
tests/testthat/helper_testthat_correctness_clvfitted.R

By definition, they are always >0 and assessing their significance is pointless

Set zval and pval of main model params to NA

---

src/pnbd_dyncov_LL.cpp

* Produces NOTES on CRAN
* As adviced in warning message

Rcpp: Replace `arma::is_finite()` with `std::isfinite()`
